# Generated by Django 6.1 on 2026-08-19 18:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['type', 'name'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'операция', 'verbose_name_plural': 'операции'},
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], default='expense', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='monthly_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Только для категорий расходов. При превышении пользователь получит предупреждение', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Лимит расходов в месяц'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_date_idx'),
        ),
    ]
