# Generated by Django 6.1 on 2026-08-20 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Идентификатор чата, куда бот шлёт отчёты', null=True, unique=True, verbose_name='Telegram ID')),
                ('link_code', models.CharField(max_length=12, unique=True, verbose_name='Код привязки')),
                ('daily_report', models.BooleanField(default=True, help_text='Присылать сводку за день в Telegram', verbose_name='Ежедневный отчёт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
    ]
