# Generated by Django 6.1 on 2026-08-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='В модели Django его нет, поэтому храним рядом с остальными настройками', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Ставится при заведении учётной записи и после сброса пароля', verbose_name='Требуется смена пароля'),
        ),
    ]
