# Generated by Django 6.1 on 2026-08-20 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_profile_middle_name_and_password_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('digest', 'Сводка за день'), ('limit', 'Превышение лимита')], max_length=20, verbose_name='Тип')),
                ('key', models.CharField(help_text='Отличает события друг от друга: дата сводки, категория и месяц лимита', max_length=100, verbose_name='Ключ события')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'key'), name='unique_notification')],
            },
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('period', models.CharField(max_length=20, verbose_name='Период')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='С')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='По')),
                ('type', models.CharField(blank=True, max_length=10, verbose_name='Тип операций')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='finance.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'сохранённый отчёт',
                'verbose_name_plural': 'сохранённые отчёты',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_report_per_user')],
            },
        ),
    ]
