# Generated by Django 6.1 on 2026-08-22 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_notifications_and_saved_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='Ключ диалога')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Шаг сценария')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные шага')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'диалог бота',
                'verbose_name_plural': 'диалоги бота',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Действие')),
                ('command', models.CharField(max_length=200, verbose_name='Команда')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('done', 'Завершено'), ('failed', 'Ошибка')], default='running', max_length=20, verbose_name='Состояние')),
                ('output', models.TextField(blank=True, verbose_name='Вывод')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_runs', to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
            ],
            options={
                'verbose_name': 'запуск обслуживания',
                'verbose_name_plural': 'запуски обслуживания',
                'ordering': ['-started_at'],
            },
        ),
    ]
